# Generated by Django 4.1 on 2022-11-10 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_username", models.CharField(max_length=50)),
                ("admin_password", models.CharField(max_length=88)),
                ("admin_email", models.EmailField(max_length=50)),
                ("admin_phone", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_username", models.CharField(max_length=50)),
                ("customer_password", models.CharField(max_length=88)),
                ("customer_email", models.EmailField(max_length=50)),
                ("customer_phone", models.CharField(max_length=30)),
                ("customer_gender", models.CharField(max_length=1)),
                ("customer_date_of_birth", models.DateField()),
                ("customer_security_question", models.IntegerField(default=0)),
                (
                    "customer_security_answer",
                    models.CharField(default="A", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionConsultation",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_purpose", models.IntegerField()),
                ("apt_area", models.IntegerField()),
                ("question_text", models.TextField()),
                ("question_status", models.IntegerField()),
                ("submission_date_time", models.DateTimeField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartment_finder_app.customer",
                    ),
                ),
            ],
        ),
    ]
