# Generated by Django 4.1 on 2022-12-09 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_username", models.CharField(max_length=50)),
                ("admin_password", models.CharField(max_length=88)),
                ("admin_email", models.EmailField(max_length=50)),
                ("admin_phone", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentInfo",
            fields=[
                ("apt_id", models.AutoField(primary_key=True, serialize=False)),
                ("apt_name", models.CharField(max_length=100)),
                ("apt_city", models.IntegerField()),
                ("apt_street", models.CharField(max_length=100)),
                ("apt_zipcode", models.CharField(max_length=20)),
                ("apt_price_low", models.IntegerField()),
                ("apt_price_high", models.IntegerField(blank=True, null=True)),
                ("apt_tag_near_campus", models.SmallIntegerField()),
                ("apt_tag_furnished", models.SmallIntegerField()),
                ("apt_tag_free_parking", models.SmallIntegerField()),
                ("apt_tag_free_we", models.SmallIntegerField()),
                ("apt_tag_free_internet", models.SmallIntegerField()),
                ("apt_url", models.URLField(max_length=300)),
                ("apt_picture_url", models.URLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_username", models.CharField(max_length=50)),
                ("customer_password", models.CharField(max_length=88)),
                ("customer_email", models.EmailField(max_length=50)),
                ("customer_phone", models.CharField(max_length=30)),
                ("customer_gender", models.CharField(max_length=1)),
                ("customer_date_of_birth", models.DateField()),
                ("customer_security_question", models.IntegerField(default=0)),
                (
                    "customer_security_answer",
                    models.CharField(default="A", max_length=50),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionConsultation",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_purpose", models.IntegerField()),
                ("apt_area", models.IntegerField()),
                ("question_text", models.TextField()),
                (
                    "question_reply",
                    models.TextField(default="Not replied yet", max_length=1000),
                ),
                ("question_status", models.IntegerField()),
                ("submission_date_time", models.DateTimeField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apartment_finder_app.customer",
                    ),
                ),
            ],
        ),
    ]
