# Generated by Django 4.1 on 2022-11-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment_finder_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApartmentInfo",
            fields=[
                ("apt_id", models.AutoField(primary_key=True, serialize=False)),
                ("apt_name", models.CharField(max_length=100)),
                ("apt_state", models.CharField(max_length=20)),
                ("apt_city", models.IntegerField()),
                ("apt_street", models.CharField(max_length=100)),
                ("apt_zipcode", models.CharField(max_length=20)),
                ("apt_price_low", models.IntegerField()),
                ("apt_price_high", models.IntegerField(blank=True, null=True)),
                ("apt_tag_near_campus", models.IntegerField()),
                ("apt_tag_furnished", models.IntegerField()),
                ("apt_tag_free_parking", models.IntegerField()),
                ("apt_tag_free_we", models.IntegerField()),
                ("apt_tag_free_internet", models.IntegerField()),
                ("apt_url", models.CharField(max_length=100)),
                ("apt_picture_url", models.CharField(max_length=100)),
            ],
        ),
    ]
