# Generated by Django 3.2.16 on 2022-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_finder_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.BigIntegerField(),
        ),
    ]
