# Generated by Django 4.1 on 2022-12-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment_finder_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=6)),
                ("code_num", models.CharField(max_length=6)),
            ],
        ),
    ]
