# Generated by Django 4.1 on 2022-11-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apartment_finder_app", "0002_apartmentinfo"),
    ]

    operations = [
        migrations.RemoveField(model_name="apartmentinfo", name="apt_state",),
    ]
