# Generated by Django 4.1 on 2022-11-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apartment_finder_app", "0003_remove_apartmentinfo_apt_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartmentinfo",
            name="apt_picture_url",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="apartmentinfo",
            name="apt_tag_free_internet",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="apartmentinfo",
            name="apt_tag_free_parking",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="apartmentinfo",
            name="apt_tag_free_we",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="apartmentinfo",
            name="apt_tag_furnished",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="apartmentinfo",
            name="apt_tag_near_campus",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="apartmentinfo",
            name="apt_url",
            field=models.URLField(max_length=300),
        ),
    ]
