# Generated by Django 3.2.16 on 2022-10-07 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_finder_app', '0004_rename_customer_questionconsultation_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionconsultation',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
