# Generated by Django 3.2.16 on 2022-10-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_finder_app', '0006_rename_customer_questionconsultation_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_password',
            field=models.CharField(max_length=77),
        ),
    ]
