# Generated by Django 3.2.16 on 2022-11-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_finder_app', '0008_auto_20221020_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_security_answer',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_security_question',
            field=models.IntegerField(default=0),
        ),
    ]
