# Generated by Django 3.2.16 on 2022-11-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_finder_app', '0009_auto_20221101_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(max_length=30),
        ),
    ]
