# Generated by Django 3.2.16 on 2022-11-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_finder_app', '0011_alter_customer_customer_security_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_security_answer',
            field=models.CharField(max_length=50),
        ),
    ]
